version: 2

models:
  - name: adv__hub_account
    description: Raw Vault hub for Account entity.
    columns:
      - name: ACCOUNT_PK
        description: Hash representation of the business key.
      - name: ACCOUNTID
        description: Business key.
      - name: LOAD_DATETIME
        description: Load datetime metadata column according to DV standards.
      - name: RECORD_SOURCE
        description: Record source metadata columns according to DV standards.
  - name: adv__hub_contact
    description: Raw Vault hub for Contact entity.
    columns:
      - name: CONTACT_PK
        description: Hash representation of the business key.
      - name: CONTACTID
        description: Business key.
      - name: LOAD_DATETIME
        description: Load datetime metadata column according to DV standards.
      - name: RECORD_SOURCE
        description: Record source metadata columns according to DV standards.
  - name: adv__hub_lead
    description: Raw Vault hub for Lead entity.
    columns:
      - name: LEAD_PK
        description: Hash representation of the business key.
      - name: LEADID
        description: Business key.
      - name: LOAD_DATETIME
        description: Load datetime metadata column according to DV standards.
      - name: RECORD_SOURCE
        description: Record source metadata columns according to DV standards.
  - name: adv__hub_opportunity
    description: Raw Vault hub for Opportunity entity.
    columns:
      - name: OPPORTUNITY_PK
        description: Hash representation of the business key.
      - name: OPPORTUNITYID
        description: Business key.
      - name: LOAD_DATETIME
        description: Load datetime metadata column according to DV standards.
      - name: RECORD_SOURCE
        description: Record source metadata columns according to DV standards.
  - name: adv__link_contact_account
    description: Raw Vault link connecting Contact and Account.
    columns:
      - name: CONTACT_ACCOUNT_PK
        description: Primary key of the link. Hash representation of concatenated foreign keys.
      - name: CONTACT_PK
        description: Hash representation of the business key.
      - name: ACCOUNT_PK
        description: Hash representation of the business key.
      - name: LOAD_DATETIME
        description: Load datetime metadata column according to DV standards.
      - name: RECORD_SOURCE
        description: Record source metadata columns according to DV standards.
  - name: adv__link_lead_contact
    description: Raw Vault link connecting Lead and Contact.
    columns:
      - name: LEAD_CONTACT_PK
        description: Primary key of the link. Hash representation of concatenated foreign keys.
      - name: LEAD_PK
        description: Hash representation of the business key.
      - name: CONTACT_PK
        description: Hash representation of the business key.
      - name: LOAD_DATETIME
        description: Load datetime metadata column according to DV standards.
      - name: RECORD_SOURCE
        description: Record source metadata columns according to DV standards.
  - name: adv__link_opportunity_account
    description: Raw Vault link connecting Opportunity and Account.
    columns:
      - name: OPPORTUNITY_ACCOUNT_PK
        description: Primary key of the link. Hash representation of concatenated foreign keys.
      - name: OPPORTUNITY_PK
        description: Hash representation of the business key.
      - name: ACCOUNT_PK
        description: Hash representation of the business key.
      - name: LOAD_DATETIME
        description: Load datetime metadata column according to DV standards.
      - name: RECORD_SOURCE
        description: Record source metadata columns according to DV standards.
  - name: adv__sat_account
    description: Raw Vault satellite for Account entity.
    columns:
      - name: ACCOUNT_PK
        description: Hash representation of the business key.
      - name: HASHDIFF
        description: Hash representation of all payload columns according to DV standards.
      - name: EFFECTIVE_FROM
        description: Applied (business) date standard columns.
      - name: LOAD_DATETIME
        description: Load datetime metadata column according to DV standards.
      - name: RECORD_SOURCE
        description: Record source metadata columns according to DV standards.
  - name: adv__sat_contact
    description: Raw Vault satellite for Contact entity.
    columns:
      - name: CONTACT_PK
        description: Hash representation of the business key.
      - name: HASHDIFF
        description: Hash representation of all payload columns according to DV standards.
      - name: EFFECTIVE_FROM
        description: Applied (business) date standard columns.
      - name: LOAD_DATETIME
        description: Load datetime metadata column according to DV standards.
      - name: RECORD_SOURCE
        description: Record source metadata columns according to DV standards.
  - name: adv__sat_lead
    description: Raw Vault satellite for Lead entity.
    columns:
      - name: LEAD_PK
        description: Hash representation of the business key.
      - name: HASHDIFF
        description: Hash representation of all payload columns according to DV standards.
      - name: EFFECTIVE_FROM
        description: Applied (business) date standard columns.
      - name: LOAD_DATETIME
        description: Load datetime metadata column according to DV standards.
      - name: RECORD_SOURCE
        description: Record source metadata columns according to DV standards.
  - name: adv__sat_opportunity
    description: Raw Vault satellite for Opportunity entity.
    columns:
      - name: OPPORTUNITY_PK
        description: Hash representation of the business key.
      - name: HASHDIFF
        description: Hash representation of all payload columns according to DV standards.
      - name: EFFECTIVE_FROM
        description: Applied (business) date standard columns.
      - name: LOAD_DATETIME
        description: Load datetime metadata column according to DV standards.
      - name: RECORD_SOURCE
        description: Record source metadata columns according to DV standards.
